version: "3.0"
services:
  db:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres_scripts:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=flaskr,fidesctl,fidesops

volumes:
  postgres:
